<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6knExQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6knExQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6knExQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createur' => ['privates', '.errored..service_locator.6knExQH.App\\Entity\\Createur', NULL, 'Cannot autowire service ".service_locator.6knExQH": it references class "App\\Entity\\Createur" but no such service exists.'],
            'createurRepository' => ['privates', 'App\\Repository\\CreateurRepository', 'getCreateurRepositoryService', true],
        ], [
            'createur' => 'App\\Entity\\Createur',
            'createurRepository' => 'App\\Repository\\CreateurRepository',
        ]);
    }
}
