<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ENjyjzyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eNjyjzy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eNjyjzy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modele' => ['privates', '.errored..service_locator.eNjyjzy.App\\Entity\\Modele', NULL, 'Cannot autowire service ".service_locator.eNjyjzy": it references class "App\\Entity\\Modele" but no such service exists.'],
        ], [
            'modele' => 'App\\Entity\\Modele',
        ]);
    }
}
