<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ud9EZdKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ud9EZdK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ud9EZdK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousCommande' => ['privates', '.errored..service_locator.ud9EZdK.App\\Entity\\SousCommande', NULL, 'Cannot autowire service ".service_locator.ud9EZdK": it references class "App\\Entity\\SousCommande" but no such service exists.'],
        ], [
            'sousCommande' => 'App\\Entity\\SousCommande',
        ]);
    }
}
