<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qd_XC3oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qd.XC3o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qd.XC3o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousCommandeRepository' => ['privates', 'App\\Repository\\SousCommandeRepository', 'getSousCommandeRepositoryService', true],
        ], [
            'sousCommandeRepository' => 'App\\Repository\\SousCommandeRepository',
        ]);
    }
}
