<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HAmfW2lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hAmfW2l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hAmfW2l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createurRepository' => ['privates', 'App\\Repository\\CreateurRepository', 'getCreateurRepositoryService', true],
        ], [
            'createurRepository' => 'App\\Repository\\CreateurRepository',
        ]);
    }
}
