<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_23v3fOEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.23v3fOE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.23v3fOE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousCommande' => ['privates', '.errored..service_locator.23v3fOE.App\\Entity\\SousCommande', NULL, 'Cannot autowire service ".service_locator.23v3fOE": it references class "App\\Entity\\SousCommande" but no such service exists.'],
            'sousCommandeRepository' => ['privates', 'App\\Repository\\SousCommandeRepository', 'getSousCommandeRepositoryService', true],
        ], [
            'sousCommande' => 'App\\Entity\\SousCommande',
            'sousCommandeRepository' => 'App\\Repository\\SousCommandeRepository',
        ]);
    }
}
