<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YdzRrbK.App\Entity\Createur' shared service.
     *
     * @return \App\Entity\Createur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YdzRrbK": it references class "App\\Entity\\Createur" but no such service exists.');
    }
}
