<?php

namespace ContainerZYShMka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousCommande2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ud9EZdK.App\Entity\SousCommande' shared service.
     *
     * @return \App\Entity\SousCommande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ud9EZdK": it references class "App\\Entity\\SousCommande" but no such service exists.');
    }
}
