<?php

namespace ContainerPHAa0xV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_33PDuuiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.33PDuui' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.33PDuui'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modele' => ['privates', '.errored..service_locator.33PDuui.App\\Entity\\Modele', NULL, 'Cannot autowire service ".service_locator.33PDuui": it references class "App\\Entity\\Modele" but no such service exists.'],
            'modeleRepository' => ['privates', 'App\\Repository\\ModeleRepository', 'getModeleRepositoryService', true],
        ], [
            'modele' => 'App\\Entity\\Modele',
            'modeleRepository' => 'App\\Repository\\ModeleRepository',
        ]);
    }
}
