<?php

namespace ContainerPHAa0xV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KhW42NZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KhW42NZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KhW42NZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommandeController::delete' => ['privates', '.service_locator.hey650R', 'get_ServiceLocator_Hey650RService', true],
            'App\\Controller\\CommandeController::edit' => ['privates', '.service_locator.hey650R', 'get_ServiceLocator_Hey650RService', true],
            'App\\Controller\\CommandeController::index' => ['privates', '.service_locator.H2oo9Vd', 'get_ServiceLocator_H2oo9VdService', true],
            'App\\Controller\\CommandeController::new' => ['privates', '.service_locator.H2oo9Vd', 'get_ServiceLocator_H2oo9VdService', true],
            'App\\Controller\\CommandeController::show' => ['privates', '.service_locator.ttJxBw.', 'get_ServiceLocator_TtJxBw_Service', true],
            'App\\Controller\\CreateurController::delete' => ['privates', '.service_locator.6knExQH', 'get_ServiceLocator_6knExQHService', true],
            'App\\Controller\\CreateurController::edit' => ['privates', '.service_locator.6knExQH', 'get_ServiceLocator_6knExQHService', true],
            'App\\Controller\\CreateurController::index' => ['privates', '.service_locator.hAmfW2l', 'get_ServiceLocator_HAmfW2lService', true],
            'App\\Controller\\CreateurController::new' => ['privates', '.service_locator.hAmfW2l', 'get_ServiceLocator_HAmfW2lService', true],
            'App\\Controller\\CreateurController::show' => ['privates', '.service_locator.YdzRrbK', 'get_ServiceLocator_YdzRrbKService', true],
            'App\\Controller\\ModeleController::delete' => ['privates', '.service_locator.33PDuui', 'get_ServiceLocator_33PDuuiService', true],
            'App\\Controller\\ModeleController::edit' => ['privates', '.service_locator.33PDuui', 'get_ServiceLocator_33PDuuiService', true],
            'App\\Controller\\ModeleController::index' => ['privates', '.service_locator.roJc7VC', 'get_ServiceLocator_RoJc7VCService', true],
            'App\\Controller\\ModeleController::new' => ['privates', '.service_locator.roJc7VC', 'get_ServiceLocator_RoJc7VCService', true],
            'App\\Controller\\ModeleController::show' => ['privates', '.service_locator.eNjyjzy', 'get_ServiceLocator_ENjyjzyService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CommandeController:delete' => ['privates', '.service_locator.hey650R', 'get_ServiceLocator_Hey650RService', true],
            'App\\Controller\\CommandeController:edit' => ['privates', '.service_locator.hey650R', 'get_ServiceLocator_Hey650RService', true],
            'App\\Controller\\CommandeController:index' => ['privates', '.service_locator.H2oo9Vd', 'get_ServiceLocator_H2oo9VdService', true],
            'App\\Controller\\CommandeController:new' => ['privates', '.service_locator.H2oo9Vd', 'get_ServiceLocator_H2oo9VdService', true],
            'App\\Controller\\CommandeController:show' => ['privates', '.service_locator.ttJxBw.', 'get_ServiceLocator_TtJxBw_Service', true],
            'App\\Controller\\CreateurController:delete' => ['privates', '.service_locator.6knExQH', 'get_ServiceLocator_6knExQHService', true],
            'App\\Controller\\CreateurController:edit' => ['privates', '.service_locator.6knExQH', 'get_ServiceLocator_6knExQHService', true],
            'App\\Controller\\CreateurController:index' => ['privates', '.service_locator.hAmfW2l', 'get_ServiceLocator_HAmfW2lService', true],
            'App\\Controller\\CreateurController:new' => ['privates', '.service_locator.hAmfW2l', 'get_ServiceLocator_HAmfW2lService', true],
            'App\\Controller\\CreateurController:show' => ['privates', '.service_locator.YdzRrbK', 'get_ServiceLocator_YdzRrbKService', true],
            'App\\Controller\\ModeleController:delete' => ['privates', '.service_locator.33PDuui', 'get_ServiceLocator_33PDuuiService', true],
            'App\\Controller\\ModeleController:edit' => ['privates', '.service_locator.33PDuui', 'get_ServiceLocator_33PDuuiService', true],
            'App\\Controller\\ModeleController:index' => ['privates', '.service_locator.roJc7VC', 'get_ServiceLocator_RoJc7VCService', true],
            'App\\Controller\\ModeleController:new' => ['privates', '.service_locator.roJc7VC', 'get_ServiceLocator_RoJc7VCService', true],
            'App\\Controller\\ModeleController:show' => ['privates', '.service_locator.eNjyjzy', 'get_ServiceLocator_ENjyjzyService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CommandeController::delete' => '?',
            'App\\Controller\\CommandeController::edit' => '?',
            'App\\Controller\\CommandeController::index' => '?',
            'App\\Controller\\CommandeController::new' => '?',
            'App\\Controller\\CommandeController::show' => '?',
            'App\\Controller\\CreateurController::delete' => '?',
            'App\\Controller\\CreateurController::edit' => '?',
            'App\\Controller\\CreateurController::index' => '?',
            'App\\Controller\\CreateurController::new' => '?',
            'App\\Controller\\CreateurController::show' => '?',
            'App\\Controller\\ModeleController::delete' => '?',
            'App\\Controller\\ModeleController::edit' => '?',
            'App\\Controller\\ModeleController::index' => '?',
            'App\\Controller\\ModeleController::new' => '?',
            'App\\Controller\\ModeleController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommandeController:delete' => '?',
            'App\\Controller\\CommandeController:edit' => '?',
            'App\\Controller\\CommandeController:index' => '?',
            'App\\Controller\\CommandeController:new' => '?',
            'App\\Controller\\CommandeController:show' => '?',
            'App\\Controller\\CreateurController:delete' => '?',
            'App\\Controller\\CreateurController:edit' => '?',
            'App\\Controller\\CreateurController:index' => '?',
            'App\\Controller\\CreateurController:new' => '?',
            'App\\Controller\\CreateurController:show' => '?',
            'App\\Controller\\ModeleController:delete' => '?',
            'App\\Controller\\ModeleController:edit' => '?',
            'App\\Controller\\ModeleController:index' => '?',
            'App\\Controller\\ModeleController:new' => '?',
            'App\\Controller\\ModeleController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
