<?php

namespace ContainerPHAa0xV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YdzRrbKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YdzRrbK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YdzRrbK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createur' => ['privates', '.errored..service_locator.YdzRrbK.App\\Entity\\Createur', NULL, 'Cannot autowire service ".service_locator.YdzRrbK": it references class "App\\Entity\\Createur" but no such service exists.'],
        ], [
            'createur' => 'App\\Entity\\Createur',
        ]);
    }
}
