<?php

namespace ContainerPHAa0xV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModeleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.33PDuui.App\Entity\Modele' shared service.
     *
     * @return \App\Entity\Modele
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.33PDuui": it references class "App\\Entity\\Modele" but no such service exists.');
    }
}
