<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerORKTU9I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerORKTU9I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerORKTU9I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerORKTU9I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerORKTU9I\App_KernelDevDebugContainer([
    'container.build_hash' => 'ORKTU9I',
    'container.build_id' => 'fa94fdc7',
    'container.build_time' => 1668255770,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerORKTU9I');
