<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZYShMka\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZYShMka/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZYShMka.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZYShMka\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZYShMka\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZYShMka',
    'container.build_id' => 'ee348c1b',
    'container.build_time' => 1665768147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZYShMka');
