<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxVIKZe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxVIKZe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxVIKZe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxVIKZe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDxVIKZe\App_KernelDevDebugContainer([
    'container.build_hash' => 'DxVIKZe',
    'container.build_id' => 'e1c8f4d5',
    'container.build_time' => 1668356542,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxVIKZe');
